namespace FarmaControl.Contracts.Inventory;

public sealed record CreateMedicationRequest(
    string? GenericName,
    string? CommercialName,
    string? TherapeuticClass,
    string? PharmaceuticalForm,
    string? Dosage,
    DateOnly? EntryDate,
    string? Origin,
    long? OriginId,
    string? Responsible,
    string? Manufacturer,
    long? ManufacturerId,
    string? Batch,
    DateOnly? ExpirationDate,
    int Quantity,
    string? Unit,
    string? Location,
    long? LocationId,
    int? MinimumQuantity,
    bool IsControlled,
    string SignaturePassword);

public sealed record UpdateMedicationRequest(
    string? GenericName,
    string? CommercialName,
    string? TherapeuticClass,
    string? PharmaceuticalForm,
    string? Dosage,
    DateOnly? EntryDate,
    string? Origin,
    long? OriginId,
    string? Responsible,
    string? Manufacturer,
    long? ManufacturerId,
    string? Batch,
    DateOnly? ExpirationDate,
    int Quantity,
    string? Unit,
    string? Location,
    long? LocationId,
    int? MinimumQuantity,
    bool IsControlled);

public sealed record MedicationResponse(
    long Id,
    string? GenericName,
    string? CommercialName,
    string? TherapeuticClass,
    string? PharmaceuticalForm,
    string? Dosage,
    DateOnly? EntryDate,
    string? Origin,
    long? OriginId,
    string? Responsible,
    string? Manufacturer,
    long? ManufacturerId,
    string? Batch,
    DateOnly? ExpirationDate,
    int Quantity,
    string? Unit,
    string? Location,
    long? LocationId,
    int MinimumQuantity,
    bool IsControlled,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt);
