// <auto-generated />
using System;
using FarmaControl.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmaControl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FarmaControlDbContext))]
    partial class FarmaControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("FarmaControl.Domain.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity");

                    b.Property<long?>("EntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Entity");

                    b.HasIndex("UserName");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.CareAppointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("doctor_name");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_emergency");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_id");

                    b.Property<string>("Responsible")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("responsible");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("care_appointments", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.Cid10Code", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.HasIndex("Code", "Name")
                        .IsUnique();

                    b.ToTable("cid10_codes", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<long>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("appointment_id");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("attendance_date");

                    b.Property<TimeOnly?>("AttendanceTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("attendance_time");

                    b.Property<string>("AttendanceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("attendance_type");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("TEXT")
                        .HasColumnName("chief_complaint");

                    b.Property<string>("Church")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("church");

                    b.Property<string>("Cid10Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("cid10_code");

                    b.Property<string>("Cid10Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("cid10_name");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentDiseaseHistory")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_disease_history");

                    b.Property<string>("DiagnosticHypothesis")
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnostic_hypothesis");

                    b.Property<bool>("HasBackSide")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_back_side");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Pastor")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("pastor");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhysicalExam")
                        .HasColumnType("TEXT")
                        .HasColumnName("physical_exam");

                    b.Property<string>("PreviousPathologicalHistory")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_pathological_history");

                    b.Property<string>("ResponsibleName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("responsible_name");

                    b.Property<string>("ResponsibleSignature")
                        .HasColumnType("TEXT")
                        .HasColumnName("responsible_signature");

                    b.Property<long?>("ResponsibleUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("responsible_user_id");

                    b.Property<int?>("ReturnNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("return_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("medical_attendances", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendanceCid10Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Cid10CodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cid10_code_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<long>("MedicalAttendanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medical_attendance_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("Cid10CodeId");

                    b.HasIndex("MedicalAttendanceId", "Cid10CodeId")
                        .IsUnique();

                    b.HasIndex("MedicalAttendanceId", "Order");

                    b.ToTable("medical_attendance_cid10_codes", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendanceDispensationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Batch")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch");

                    b.Property<DateTimeOffset?>("DispensedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("dispensed_at");

                    b.Property<long>("MedicalAttendanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medical_attendance_id");

                    b.Property<long?>("MedicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medication_id");

                    b.Property<string>("MedicationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("medication_name");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<long?>("PrescriptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prescription_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("Responsible")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("responsible");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("MedicalAttendanceId", "Order");

                    b.ToTable("medical_attendance_dispensations", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendanceNursingCheckItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("MedicalAttendanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medical_attendance_id");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("MedicalAttendanceId", "Order");

                    b.ToTable("medical_attendance_nursing_checks", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendancePrescriptionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Directions")
                        .HasColumnType("TEXT")
                        .HasColumnName("directions");

                    b.Property<string>("Dosage")
                        .HasColumnType("TEXT")
                        .HasColumnName("dosage");

                    b.Property<long>("MedicalAttendanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medical_attendance_id");

                    b.Property<long?>("MedicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medication_id");

                    b.Property<string>("MedicationName")
                        .HasColumnType("TEXT")
                        .HasColumnName("medication_name");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("MedicalAttendanceId", "Order");

                    b.ToTable("medical_attendance_prescriptions", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Anamnesis")
                        .HasColumnType("TEXT")
                        .HasColumnName("anamnesis");

                    b.Property<long>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("appointment_id");

                    b.Property<string>("Cid10")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("cid10");

                    b.Property<string>("Conduct")
                        .HasColumnType("TEXT")
                        .HasColumnName("conduct");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DiagnosticHypothesis")
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnostic_hypothesis");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("doctor_name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhysicalExam")
                        .HasColumnType("TEXT")
                        .HasColumnName("physical_exam");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("medical_records", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cpf")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Comorbidities")
                        .HasColumnType("TEXT")
                        .HasColumnName("comorbidities");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Sex")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("sex");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.Prescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Directions")
                        .HasColumnType("TEXT")
                        .HasColumnName("directions");

                    b.Property<DateTimeOffset?>("DispensedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("dispensed_at");

                    b.Property<string>("Dosage")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("dosage");

                    b.Property<bool>("IsDispensed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_dispensed");

                    b.Property<long>("MedicalRecordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medical_record_id");

                    b.Property<long?>("MedicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medication_id");

                    b.Property<string>("MedicationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("medication_name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patient_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("IsDispensed");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PatientId");

                    b.ToTable("prescriptions", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.TriageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("appointment_id");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("blood_pressure");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("TEXT")
                        .HasColumnName("chief_complaint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("HeartRate")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("heart_rate");

                    b.Property<string>("Height")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("height");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("OxygenSaturation")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("oxygen_saturation");

                    b.Property<string>("Responsible")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("responsible");

                    b.Property<string>("Temperature")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Weight")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("triage_records", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Inventory.Donor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("donors", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Inventory.Manufacturer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Inventory.Medication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Batch")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch");

                    b.Property<string>("CommercialName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("commercial_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Dosage")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("dosage");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_date");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration_date");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("generic_name");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_controlled");

                    b.Property<string>("Location")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<long?>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<long?>("ManufacturerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minimum_quantity");

                    b.Property<string>("Origin")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<long?>("OriginId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("origin_id");

                    b.Property<string>("PharmaceuticalForm")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("pharmaceutical_form");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("Responsible")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("responsible");

                    b.Property<string>("TherapeuticClass")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("therapeutic_class");

                    b.Property<string>("Unit")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Batch");

                    b.HasIndex("CommercialName");

                    b.HasIndex("ExpirationDate");

                    b.HasIndex("GenericName");

                    b.HasIndex("LocationId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OriginId");

                    b.ToTable("medications", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Inventory.StockLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("stock_locations", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Inventory.StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("appointment_id");

                    b.Property<long?>("AttendanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attendance_id");

                    b.Property<string>("Batch")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<long>("MedicationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medication_id");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long?>("PrescriptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prescription_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("responsible");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("Date");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("Type");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccessRevocationReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("access_revocation_reason");

                    b.Property<DateTimeOffset?>("AccessRevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("access_revoked_at");

                    b.Property<long?>("AccessRevokedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_revoked_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SignaturePasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("signature_password_hash");

                    b.Property<bool>("SignaturePasswordResetRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("signature_password_reset_required");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("is_deleted = 0");

                    b.HasIndex("IsDeleted");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Users.UserModuleAccess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("GrantedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("granted_by_user_id");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("module");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<long?>("RevokedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Module")
                        .IsUnique();

                    b.ToTable("user_module_accesses", (string)null);
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendance", b =>
                {
                    b.OwnsOne("FarmaControl.Domain.Care.VitalSigns", "VitalSigns", b1 =>
                        {
                            b1.Property<long>("MedicalAttendanceId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("BloodGlucose")
                                .HasPrecision(7, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("blood_glucose");

                            b1.Property<int?>("DiastolicPressure")
                                .HasColumnType("INTEGER")
                                .HasColumnName("diastolic_pressure");

                            b1.Property<int?>("HeartRate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("heart_rate");

                            b1.Property<int?>("OxygenSaturation")
                                .HasColumnType("INTEGER")
                                .HasColumnName("oxygen_saturation");

                            b1.Property<int?>("SystolicPressure")
                                .HasColumnType("INTEGER")
                                .HasColumnName("systolic_pressure");

                            b1.Property<decimal?>("Temperature")
                                .HasPrecision(5, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("temperature");

                            b1.HasKey("MedicalAttendanceId");

                            b1.ToTable("medical_attendances");

                            b1.WithOwner()
                                .HasForeignKey("MedicalAttendanceId");
                        });

                    b.Navigation("VitalSigns")
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendanceCid10Item", b =>
                {
                    b.HasOne("FarmaControl.Domain.Care.Cid10Code", null)
                        .WithMany()
                        .HasForeignKey("Cid10CodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmaControl.Domain.Care.MedicalAttendance", null)
                        .WithMany("Cid10Codes")
                        .HasForeignKey("MedicalAttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendanceDispensationItem", b =>
                {
                    b.HasOne("FarmaControl.Domain.Care.MedicalAttendance", null)
                        .WithMany("Dispensations")
                        .HasForeignKey("MedicalAttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendanceNursingCheckItem", b =>
                {
                    b.HasOne("FarmaControl.Domain.Care.MedicalAttendance", null)
                        .WithMany("NursingChecks")
                        .HasForeignKey("MedicalAttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendancePrescriptionItem", b =>
                {
                    b.HasOne("FarmaControl.Domain.Care.MedicalAttendance", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalAttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaControl.Domain.Users.UserModuleAccess", b =>
                {
                    b.HasOne("FarmaControl.Domain.Users.User", null)
                        .WithMany("ModuleAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaControl.Domain.Care.MedicalAttendance", b =>
                {
                    b.Navigation("Cid10Codes");

                    b.Navigation("Dispensations");

                    b.Navigation("NursingChecks");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("FarmaControl.Domain.Users.User", b =>
                {
                    b.Navigation("ModuleAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
