namespace FarmaControl.Contracts.Care;

public sealed record CreateMedicalAttendanceRequest(
    long PatientId,
    long? ResponsibleUserId,
    string? ResponsibleName,
    string Name,
    int? Age,
    DateOnly AttendanceDate,
    TimeOnly? AttendanceTime,
    string? City,
    string? Church,
    string? Pastor,
    string AttendanceType,
    int? ReturnNumber,
    VitalSignsRequest? VitalSigns,
    string? ChiefComplaint,
    string? PreviousPathologicalHistory,
    string? CurrentDiseaseHistory,
    string? PhysicalExam,
    IReadOnlyList<MedicalAttendancePrescriptionItemRequest> Prescriptions,
    IReadOnlyList<MedicalAttendanceNursingCheckItemRequest> NursingChecks,
    IReadOnlyList<MedicalAttendanceDispensationItemRequest> Dispensations,
    string? ResponsibleSignature,
    bool HasBackSide,
    string SignaturePassword,
    string? DiagnosticHypothesis = null,
    string? Cid10Code = null,
    string? Cid10Name = null,
    IReadOnlyList<MedicalAttendanceCid10Request>? Cid10Codes = null);

public sealed record UpdateMedicalAttendanceRequest(
    VitalSignsRequest? VitalSigns,
    string? ChiefComplaint,
    string? PreviousPathologicalHistory,
    string? CurrentDiseaseHistory,
    string? PhysicalExam,
    IReadOnlyList<MedicalAttendancePrescriptionItemRequest> Prescriptions,
    IReadOnlyList<MedicalAttendanceNursingCheckItemRequest> NursingChecks,
    IReadOnlyList<MedicalAttendanceDispensationItemRequest> Dispensations,
    string? ResponsibleSignature,
    bool HasBackSide,
    string SignaturePassword,
    string? DiagnosticHypothesis = null,
    string? Cid10Code = null,
    string? Cid10Name = null,
    IReadOnlyList<MedicalAttendanceCid10Request>? Cid10Codes = null);

public sealed record MedicalAttendanceResponse(
    long Id,
    long AppointmentId,
    long PatientId,
    long? ResponsibleUserId,
    string? ResponsibleName,
    string Name,
    int? Age,
    DateOnly AttendanceDate,
    TimeOnly? AttendanceTime,
    string? City,
    string? Church,
    string? Pastor,
    string AttendanceType,
    int? ReturnNumber,
    VitalSignsResponse VitalSigns,
    string? ChiefComplaint,
    string? PreviousPathologicalHistory,
    string? CurrentDiseaseHistory,
    string? PhysicalExam,
    IReadOnlyList<MedicalAttendancePrescriptionItemResponse> Prescriptions,
    IReadOnlyList<MedicalAttendanceNursingCheckItemResponse> NursingChecks,
    IReadOnlyList<MedicalAttendanceDispensationItemResponse> Dispensations,
    string? ResponsibleSignature,
    bool HasBackSide,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt,
    string? DiagnosticHypothesis,
    string? Cid10Code,
    string? Cid10Name,
    IReadOnlyList<MedicalAttendanceCid10Response> Cid10Codes,
    long? TriageResponsibleUserId = null,
    string? TriageResponsibleName = null,
    string? TriageResponsibleSignature = null,
    long? MedicalResponsibleUserId = null,
    string? MedicalResponsibleName = null,
    string? MedicalResponsibleSignature = null,
    long? DispensationResponsibleUserId = null,
    string? DispensationResponsibleName = null,
    string? DispensationResponsibleSignature = null);

public sealed record MedicalAttendanceCid10Request(
    int Order,
    long Cid10CodeId,
    string Code,
    string Name);

public sealed record MedicalAttendanceCid10Response(
    long Id,
    int Order,
    long Cid10CodeId,
    string Code,
    string Name);
